services:
  gazpar2haws:
    build:
      context: .
      dockerfile: Dockerfile
    image: ssenart/gazpar2haws:latest
    container_name: gazpar2haws
    restart: unless-stopped
    network_mode: bridge
    user: "1000:1000"
    volumes:
      - ./docker/config:/app/config
      - ./docker/log:/app/log
    env_file: config/secrets.env
